-- =============================================================================
-- Insurance Trust Hub - Seed Data
-- 50 realistic insurance providers across major US markets
-- =============================================================================

-- Clear existing seed data (safe for re-runs in development)
TRUNCATE TABLE reviews, leads, providers RESTART IDENTITY CASCADE;

INSERT INTO providers (
  id, slug, name, provider_type, categories, states_licensed, cities,
  license_info, specialties, rating, review_count, years_in_business,
  relocation_experience, verified, description, short_description, contact
) VALUES

-- Florida (8 providers)
(
  'a1000001-0001-4000-8000-000000000001',
  'sunshine-coast-insurance-group',
  'Sunshine Coast Insurance Group',
  'brokerage',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['FL', 'GA'],
  ARRAY['Miami', 'Fort Lauderdale', 'West Palm Beach'],
  '{"licenses":[{"state":"FL","license_number":"L0458721","type":"Property & Casualty","verification_url":"https://www.myfloridalicense.com/LicenseDetail.asp?LicNum=L0458721"},{"state":"GA","license_number":"G1982345","type":"Property & Casualty","verification_url":"https://oci.georgia.gov/verify-license"}]}',
  ARRAY['Relocation Experienced', 'Bundle Experts', 'Hurricane Coverage'],
  4.8, 187, 22, TRUE, TRUE,
  'Sunshine Coast Insurance Group has served South Florida families and relocators for over two decades. Our bilingual team specializes in coastal property coverage, auto bundling, and helping newcomers navigate Florida''s unique insurance landscape including windstorm and flood considerations.',
  'South Florida brokerage specializing in coastal homeowners and relocation insurance.',
  '{"phone":"(305) 555-0142","email":"quotes@sunshinecoastins.com","website":"https://www.sunshinecoastins.com","address":{"street":"1200 Brickell Ave, Suite 800","city":"Miami","state":"FL","zip":"33131"}}'
),
(
  'a1000001-0001-4000-8000-000000000002',
  'gulf-breeze-independent-agents',
  'Gulf Breeze Independent Agents',
  'independent_agent',
  ARRAY['homeowners', 'auto'],
  ARRAY['FL', 'AL'],
  ARRAY['Tampa', 'St. Petersburg', 'Clearwater'],
  '{"licenses":[{"state":"FL","license_number":"A0892341","type":"Property & Casualty","verification_url":"https://www.myfloridalicense.com/LicenseDetail.asp?LicNum=A0892341"}]}',
  ARRAY['Bundle Experts', 'First-Time Homebuyers'],
  4.5, 94, 15, FALSE, TRUE,
  'As independent agents, we shop multiple carriers to find the best homeowners and auto rates for Tampa Bay residents. No single-company bias—just honest comparisons and local expertise.',
  'Independent Tampa Bay agent comparing top carriers for home and auto.',
  '{"phone":"(813) 555-0198","email":"info@gulfbreezeagents.com","website":"https://www.gulfbreezeagents.com","address":{"street":"401 N Ashley Dr","city":"Tampa","state":"FL","zip":"33602"}}'
),
(
  'a1000001-0001-4000-8000-000000000003',
  'palm-beach-medicare-advisors',
  'Palm Beach Medicare Advisors',
  'specialist',
  ARRAY['medicare', 'health'],
  ARRAY['FL'],
  ARRAY['West Palm Beach', 'Boca Raton', 'Delray Beach'],
  '{"licenses":[{"state":"FL","license_number":"H0567123","type":"Health & Life","verification_url":"https://www.myfloridalicense.com/LicenseDetail.asp?LicNum=H0567123"}]}',
  ARRAY['Medicare Specialists', 'Senior Relocation', 'Supplement Plans'],
  4.9, 312, 18, TRUE, TRUE,
  'Palm Beach Medicare Advisors is a dedicated Medicare specialist firm helping seniors compare Advantage, Supplement, and Part D plans. We guide snowbirds and retirees relocating to Florida through every enrollment window.',
  'Medicare specialists serving Palm Beach County seniors and retirees.',
  '{"phone":"(561) 555-0167","email":"advisors@pbmedicare.com","website":"https://www.pbmedicare.com","address":{"street":"777 S Flagler Dr, Suite 300","city":"West Palm Beach","state":"FL","zip":"33401"}}'
),
(
  'a1000001-0001-4000-8000-000000000004',
  'orlando-family-insurance',
  'Orlando Family Insurance',
  'independent_agent',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['FL'],
  ARRAY['Orlando', 'Kissimmee', 'Winter Park'],
  '{"licenses":[{"state":"FL","license_number":"A1023456","type":"Property & Casualty","verification_url":"https://www.myfloridalicense.com/LicenseDetail.asp?LicNum=A1023456"}]}',
  ARRAY['Bundle Experts', 'Disney Area Relocation'],
  4.3, 67, 11, TRUE, TRUE,
  'Orlando Family Insurance helps Central Florida families and theme-park area transplants secure affordable homeowners, renters, and auto coverage with personalized service.',
  'Central Florida independent agent for families and renters.',
  '{"phone":"(407) 555-0134","email":"hello@orlandofamilyins.com","website":"https://www.orlandofamilyins.com","address":{"street":"255 S Orange Ave","city":"Orlando","state":"FL","zip":"32801"}}'
),
(
  'a1000001-0001-4000-8000-000000000005',
  'jacksonville-harbor-insurance',
  'Jacksonville Harbor Insurance',
  'brokerage',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['FL', 'SC'],
  ARRAY['Jacksonville', 'St. Augustine'],
  '{"licenses":[{"state":"FL","license_number":"L0789012","type":"Property & Casualty","verification_url":"https://www.myfloridalicense.com/LicenseDetail.asp?LicNum=L0789012"}]}',
  ARRAY['Relocation Experienced', 'Military Families', 'Bundle Experts'],
  4.6, 143, 19, TRUE, TRUE,
  'Jacksonville Harbor Insurance serves Navy families, corporate relocators, and longtime residents with comprehensive property and auto solutions across Northeast Florida.',
  'Northeast Florida brokerage with military and relocation expertise.',
  '{"phone":"(904) 555-0189","email":"contact@jaxharborins.com","website":"https://www.jaxharborins.com","address":{"street":"50 N Laura St, Suite 1200","city":"Jacksonville","state":"FL","zip":"32202"}}'
),
(
  'a1000001-0001-4000-8000-000000000006',
  'naples-luxury-property-insurance',
  'Naples Luxury Property Insurance',
  'specialist',
  ARRAY['homeowners'],
  ARRAY['FL'],
  ARRAY['Naples', 'Marco Island', 'Bonita Springs'],
  '{"licenses":[{"state":"FL","license_number":"S0345678","type":"Property & Casualty","verification_url":"https://www.myfloridalicense.com/LicenseDetail.asp?LicNum=S0345678"}]}',
  ARRAY['High-Value Property', 'Coastal Estates', 'Art & Jewelry Riders'],
  4.7, 89, 25, FALSE, TRUE,
  'We insure Southwest Florida''s finest homes with tailored high-value property policies, excess liability coverage, and white-glove claims advocacy for waterfront estates.',
  'High-value homeowners specialist for Naples and SW Florida coast.',
  '{"phone":"(239) 555-0156","email":"concierge@naplesluxuryins.com","website":"https://www.naplesluxuryins.com","address":{"street":"880 Fifth Ave S, Suite 200","city":"Naples","state":"FL","zip":"34102"}}'
),
(
  'a1000001-0001-4000-8000-000000000007',
  'tallahassee-capital-insurance',
  'Tallahassee Capital Insurance',
  'independent_agent',
  ARRAY['auto', 'renters', 'homeowners'],
  ARRAY['FL', 'GA', 'AL'],
  ARRAY['Tallahassee'],
  '{"licenses":[{"state":"FL","license_number":"A0678901","type":"Property & Casualty","verification_url":"https://www.myfloridalicense.com/LicenseDetail.asp?LicNum=A0678901"}]}',
  ARRAY['Student & Young Professional', 'Bundle Experts'],
  4.1, 42, 8, FALSE, TRUE,
  'Tallahassee Capital Insurance offers budget-friendly renters and auto policies for FSU students, state employees, and young professionals starting out in the capital city.',
  'Affordable renters and auto coverage for Tallahassee residents.',
  '{"phone":"(850) 555-0173","email":"info@tallycapitalins.com","website":"https://www.tallycapitalins.com","address":{"street":"200 S Duval St","city":"Tallahassee","state":"FL","zip":"32301"}}'
),
(
  'a1000001-0001-4000-8000-000000000008',
  'sarasota-bay-health-partners',
  'Sarasota Bay Health Partners',
  'specialist',
  ARRAY['health', 'medicare'],
  ARRAY['FL'],
  ARRAY['Sarasota', 'Bradenton', 'Venice'],
  '{"licenses":[{"state":"FL","license_number":"H0234567","type":"Health & Life","verification_url":"https://www.myfloridalicense.com/LicenseDetail.asp?LicNum=H0234567"}]}',
  ARRAY['Medicare Specialists', 'ACA Marketplace', 'Small Business Health'],
  4.4, 76, 14, TRUE, TRUE,
  'Sarasota Bay Health Partners navigates individual health plans, Medicare options, and small group benefits for Gulf Coast residents and seasonal relocators.',
  'Health and Medicare specialist for Sarasota-Manatee counties.',
  '{"phone":"(941) 555-0128","email":"enroll@sarasotahealth.com","website":"https://www.sarasotahealth.com","address":{"street":"1990 Main St, Suite 750","city":"Sarasota","state":"FL","zip":"34236"}}'
),

-- Texas (8 providers)
(
  'a1000002-0002-4000-8000-000000000001',
  'lone-star-insurance-brokers',
  'Lone Star Insurance Brokers',
  'brokerage',
  ARRAY['homeowners', 'auto'],
  ARRAY['TX', 'OK', 'NM'],
  ARRAY['Houston', 'Sugar Land', 'The Woodlands'],
  '{"licenses":[{"state":"TX","license_number":"1234567","type":"Property & Casualty","verification_url":"https://www.tdi.texas.gov/agent/index.html"},{"state":"OK","license_number":"OK-987654","type":"Property & Casualty","verification_url":"https://www.oid.ok.gov/"}]}',
  ARRAY['Relocation Experienced', 'Bundle Experts', 'Flood & Wind'],
  4.7, 203, 28, TRUE, TRUE,
  'Lone Star Insurance Brokers is Houston''s trusted partner for homeowners and auto coverage, with deep expertise in Gulf Coast weather risks and corporate relocation packages.',
  'Houston brokerage for home, auto, and relocation coverage.',
  '{"phone":"(713) 555-0145","email":"quotes@lonestarbrokers.com","website":"https://www.lonestarbrokers.com","address":{"street":"1000 Louisiana St, Suite 2400","city":"Houston","state":"TX","zip":"77002"}}'
),
(
  'a1000002-0002-4000-8000-000000000002',
  'austin-tech-insurance-co',
  'Austin Tech Insurance Co.',
  'independent_agent',
  ARRAY['renters', 'auto', 'homeowners'],
  ARRAY['TX'],
  ARRAY['Austin', 'Round Rock', 'Cedar Park'],
  '{"licenses":[{"state":"TX","license_number":"2345678","type":"Property & Casualty","verification_url":"https://www.tdi.texas.gov/agent/index.html"}]}',
  ARRAY['Tech Relocation', 'Bundle Experts', 'Electric Vehicle Coverage'],
  4.6, 156, 12, TRUE, TRUE,
  'Austin Tech Insurance Co. caters to the city''s booming tech workforce with fast renters quotes, EV-friendly auto policies, and guidance for first-time Texas homebuyers.',
  'Austin independent agent for tech workers and new residents.',
  '{"phone":"(512) 555-0191","email":"hello@austintechins.com","website":"https://www.austintechins.com","address":{"street":"301 Congress Ave, Suite 500","city":"Austin","state":"TX","zip":"78701"}}'
),
(
  'a1000002-0002-4000-8000-000000000003',
  'dallas-metro-insurance-group',
  'Dallas Metro Insurance Group',
  'brokerage',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['TX'],
  ARRAY['Dallas', 'Plano', 'Frisco', 'Irving'],
  '{"licenses":[{"state":"TX","license_number":"3456789","type":"Property & Casualty","verification_url":"https://www.tdi.texas.gov/agent/index.html"}]}',
  ARRAY['High-Value Property', 'Bundle Experts', 'Corporate Relocation'],
  4.8, 241, 31, TRUE, TRUE,
  'Dallas Metro Insurance Group provides premium homeowners coverage for North Texas estates alongside competitive auto and renters policies for DFW''s growing population.',
  'DFW brokerage for high-value homes and corporate relocations.',
  '{"phone":"(214) 555-0162","email":"info@dallasmetroins.com","website":"https://www.dallasmetroins.com","address":{"street":"2001 Ross Ave, Suite 700","city":"Dallas","state":"TX","zip":"75201"}}'
),
(
  'a1000002-0002-4000-8000-000000000004',
  'san-antonio-heritage-agents',
  'San Antonio Heritage Agents',
  'independent_agent',
  ARRAY['homeowners', 'auto'],
  ARRAY['TX'],
  ARRAY['San Antonio', 'New Braunfels', 'Boerne'],
  '{"licenses":[{"state":"TX","license_number":"4567890","type":"Property & Casualty","verification_url":"https://www.tdi.texas.gov/agent/index.html"}]}',
  ARRAY['Military Families', 'Bundle Experts', 'Bilingual Service'],
  4.4, 98, 17, TRUE, TRUE,
  'San Antonio Heritage Agents proudly serves military families at Joint Base San Antonio and local homeowners with bilingual support and multi-carrier comparisons.',
  'Military-focused independent agent in San Antonio.',
  '{"phone":"(210) 555-0137","email":"service@saheritage.com","website":"https://www.saheritage.com","address":{"street":"745 E Mulberry Ave","city":"San Antonio","state":"TX","zip":"78212"}}'
),
(
  'a1000002-0002-4000-8000-000000000005',
  'fort-worth-ranch-insurance',
  'Fort Worth Ranch Insurance',
  'specialist',
  ARRAY['homeowners', 'auto'],
  ARRAY['TX', 'OK'],
  ARRAY['Fort Worth', 'Arlington', 'Weatherford'],
  '{"licenses":[{"state":"TX","license_number":"5678901","type":"Property & Casualty","verification_url":"https://www.tdi.texas.gov/agent/index.html"}]}',
  ARRAY['Ranch & Acreage', 'High-Value Property', 'Livestock Liability'],
  4.5, 71, 23, FALSE, TRUE,
  'Fort Worth Ranch Insurance specializes in acreage properties, barns, workshops, and ranch vehicles across the Metroplex and surrounding rural counties.',
  'Ranch and acreage insurance specialist for Fort Worth area.',
  '{"phone":"(817) 555-0184","email":"ranch@fwinsurance.com","website":"https://www.fwinsurance.com","address":{"street":"777 Main St, Suite 600","city":"Fort Worth","state":"TX","zip":"76102"}}'
),
(
  'a1000002-0002-4000-8000-000000000006',
  'el-paso-border-health-insurance',
  'El Paso Border Health Insurance',
  'specialist',
  ARRAY['health', 'medicare'],
  ARRAY['TX', 'NM'],
  ARRAY['El Paso', 'Las Cruces'],
  '{"licenses":[{"state":"TX","license_number":"6789012","type":"Health & Life","verification_url":"https://www.tdi.texas.gov/agent/index.html"}]}',
  ARRAY['Medicare Specialists', 'Bilingual Service', 'Cross-Border Families'],
  4.2, 53, 10, TRUE, TRUE,
  'El Paso Border Health Insurance helps families on both sides of the border navigate Texas and New Mexico health plans, Medicare enrollment, and supplemental coverage.',
  'Bilingual health and Medicare specialist for El Paso region.',
  '{"phone":"(915) 555-0159","email":"citas@epborderhealth.com","website":"https://www.epborderhealth.com","address":{"street":"221 N Kansas St, Suite 400","city":"El Paso","state":"TX","zip":"79901"}}'
),
(
  'a1000002-0002-4000-8000-000000000007',
  'corpus-christi-coastal-insurance',
  'Corpus Christi Coastal Insurance',
  'brokerage',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['TX'],
  ARRAY['Corpus Christi', 'Port Aransas', 'Rockport'],
  '{"licenses":[{"state":"TX","license_number":"7890123","type":"Property & Casualty","verification_url":"https://www.tdi.texas.gov/agent/index.html"}]}',
  ARRAY['Coastal Coverage', 'Hurricane Deductibles', 'Relocation Experienced'],
  4.3, 64, 16, TRUE, TRUE,
  'Corpus Christi Coastal Insurance understands Gulf Coast windstorm pools, flood zones, and the insurance needs of beach-town residents and seasonal relocators.',
  'Coastal Texas brokerage for windstorm and flood coverage.',
  '{"phone":"(361) 555-0176","email":"coastal@ccinsurance.com","website":"https://www.ccinsurance.com","address":{"street":"600 N Shoreline Blvd, Suite 300","city":"Corpus Christi","state":"TX","zip":"78401"}}'
),
(
  'a1000002-0002-4000-8000-000000000008',
  'lubbock-plains-auto-home',
  'Lubbock Plains Auto & Home',
  'independent_agent',
  ARRAY['auto', 'homeowners', 'renters'],
  ARRAY['TX', 'NM'],
  ARRAY['Lubbock', 'Amarillo'],
  '{"licenses":[{"state":"TX","license_number":"8901234","type":"Property & Casualty","verification_url":"https://www.tdi.texas.gov/agent/index.html"}]}',
  ARRAY['Bundle Experts', 'Farm & Ranch'],
  3.9, 38, 9, FALSE, TRUE,
  'Lubbock Plains Auto & Home delivers straightforward, affordable coverage for West Texas families, college students, and agricultural property owners.',
  'West Texas independent agent for auto and home coverage.',
  '{"phone":"(806) 555-0123","email":"info@lubbockplains.com","website":"https://www.lubbockplains.com","address":{"street":"1500 Broadway, Suite 200","city":"Lubbock","state":"TX","zip":"79401"}}'
),

-- California (8 providers)
(
  'a1000003-0003-4000-8000-000000000001',
  'pacific-shield-insurance-group',
  'Pacific Shield Insurance Group',
  'brokerage',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['CA', 'OR', 'WA'],
  ARRAY['Los Angeles', 'Santa Monica', 'Pasadena'],
  '{"licenses":[{"state":"CA","license_number":"0B12345","type":"Property & Casualty","verification_url":"https://www.insurance.ca.gov/0200-industry/0070-check-license-status/"},{"state":"OR","license_number":"OR-556677","type":"Property & Casualty","verification_url":"https://dfr.oregon.gov/"}]}',
  ARRAY['Earthquake Coverage', 'High-Value Property', 'Relocation Experienced'],
  4.7, 198, 26, TRUE, TRUE,
  'Pacific Shield Insurance Group protects Southern California homeowners with earthquake riders, wildfire mitigation guidance, and comprehensive auto-renters bundles.',
  'SoCal brokerage for earthquake, wildfire, and home coverage.',
  '{"phone":"(310) 555-0148","email":"shield@pacificshield.com","website":"https://www.pacificshield.com","address":{"street":"10960 Wilshire Blvd, Suite 1400","city":"Los Angeles","state":"CA","zip":"90024"}}'
),
(
  'a1000003-0003-4000-8000-000000000002',
  'bay-area-benefits-advisors',
  'Bay Area Benefits Advisors',
  'specialist',
  ARRAY['health', 'medicare'],
  ARRAY['CA'],
  ARRAY['San Francisco', 'Oakland', 'San Jose'],
  '{"licenses":[{"state":"CA","license_number":"0H67890","type":"Health & Life","verification_url":"https://www.insurance.ca.gov/0200-industry/0070-check-license-status/"}]}',
  ARRAY['Medicare Specialists', 'Tech Employee Benefits', 'ACA Marketplace'],
  4.9, 267, 20, TRUE, TRUE,
  'Bay Area Benefits Advisors helps tech transplants and longtime residents compare Covered California plans, employer transitions, and Medicare supplements.',
  'Health and Medicare specialist for San Francisco Bay Area.',
  '{"phone":"(415) 555-0193","email":"advisors@bayareabenefits.com","website":"https://www.bayareabenefits.com","address":{"street":"1 Market St, Suite 3600","city":"San Francisco","state":"CA","zip":"94105"}}'
),
(
  'a1000003-0003-4000-8000-000000000003',
  'san-diego-sunshine-insurance',
  'San Diego Sunshine Insurance',
  'independent_agent',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['CA'],
  ARRAY['San Diego', 'La Jolla', 'Carlsbad'],
  '{"licenses":[{"state":"CA","license_number":"0A23456","type":"Property & Casualty","verification_url":"https://www.insurance.ca.gov/0200-industry/0070-check-license-status/"}]}',
  ARRAY['Military Families', 'Bundle Experts', 'Relocation Experienced'],
  4.6, 134, 14, TRUE, TRUE,
  'San Diego Sunshine Insurance serves Navy families, biotech professionals, and beach community residents with tailored property and vehicle coverage.',
  'San Diego agent for military families and coastal living.',
  '{"phone":"(619) 555-0165","email":"sunny@sandiegoins.com","website":"https://www.sandiegoins.com","address":{"street":"750 B St, Suite 1930","city":"San Diego","state":"CA","zip":"92101"}}'
),
(
  'a1000003-0003-4000-8000-000000000004',
  'sacramento-valley-insurance',
  'Sacramento Valley Insurance',
  'brokerage',
  ARRAY['homeowners', 'auto'],
  ARRAY['CA', 'NV'],
  ARRAY['Sacramento', 'Roseville', 'Folsom'],
  '{"licenses":[{"state":"CA","license_number":"0L34567","type":"Property & Casualty","verification_url":"https://www.insurance.ca.gov/0200-industry/0070-check-license-status/"}]}',
  ARRAY['Wildfire Mitigation', 'Bundle Experts', 'State Employee Discounts'],
  4.4, 87, 18, FALSE, TRUE,
  'Sacramento Valley Insurance helps capital region homeowners navigate wildfire risk scoring while offering competitive auto bundles for state workers and suburban families.',
  'Sacramento brokerage with wildfire and bundle expertise.',
  '{"phone":"(916) 555-0131","email":"valley@sacinsurance.com","website":"https://www.sacinsurance.com","address":{"street":"980 9th St, Suite 2000","city":"Sacramento","state":"CA","zip":"95814"}}'
),
(
  'a1000003-0003-4000-8000-000000000005',
  'orange-county-luxury-insurance',
  'Orange County Luxury Insurance',
  'specialist',
  ARRAY['homeowners', 'auto'],
  ARRAY['CA'],
  ARRAY['Irvine', 'Newport Beach', 'Laguna Beach'],
  '{"licenses":[{"state":"CA","license_number":"0S45678","type":"Property & Casualty","verification_url":"https://www.insurance.ca.gov/0200-industry/0070-check-license-status/"}]}',
  ARRAY['High-Value Property', 'Collector Vehicles', 'Umbrella Liability'],
  4.8, 112, 22, FALSE, TRUE,
  'Orange County Luxury Insurance provides bespoke coverage for coastal estates, luxury vehicles, and high-net-worth families throughout OC''s premier communities.',
  'High-value property and auto specialist for Orange County.',
  '{"phone":"(949) 555-0187","email":"luxury@ocinsurance.com","website":"https://www.ocinsurance.com","address":{"street":"520 Newport Center Dr, Suite 600","city":"Newport Beach","state":"CA","zip":"92660"}}'
),
(
  'a1000003-0003-4000-8000-000000000006',
  'fresno-central-valley-agents',
  'Fresno Central Valley Agents',
  'independent_agent',
  ARRAY['auto', 'homeowners', 'renters'],
  ARRAY['CA'],
  ARRAY['Fresno', 'Clovis', 'Madera'],
  '{"licenses":[{"state":"CA","license_number":"0A56789","type":"Property & Casualty","verification_url":"https://www.insurance.ca.gov/0200-industry/0070-check-license-status/"}]}',
  ARRAY['Agricultural Property', 'Bundle Experts'],
  4.0, 45, 13, FALSE, TRUE,
  'Fresno Central Valley Agents offer practical homeowners, renters, and auto insurance for farm communities, agricultural businesses, and Central Valley families.',
  'Central Valley independent agent for farm and family coverage.',
  '{"phone":"(559) 555-0154","email":"agents@fresnocentral.com","website":"https://www.fresnocentral.com","address":{"street":"5260 N Palm Ave, Suite 122","city":"Fresno","state":"CA","zip":"93704"}}'
),
(
  'a1000003-0003-4000-8000-000000000007',
  'silicon-valley-renters-insurance',
  'Silicon Valley Renters Insurance',
  'specialist',
  ARRAY['renters', 'auto'],
  ARRAY['CA'],
  ARRAY['Palo Alto', 'Mountain View', 'Sunnyvale'],
  '{"licenses":[{"state":"CA","license_number":"0R67890","type":"Property & Casualty","verification_url":"https://www.insurance.ca.gov/0200-industry/0070-check-license-status/"}]}',
  ARRAY['Tech Relocation', 'Renters Specialists', 'Liability Coverage'],
  4.5, 91, 7, TRUE, TRUE,
  'Silicon Valley Renters Insurance focuses exclusively on fast, affordable renters and auto policies for tech employees, interns, and apartment dwellers.',
  'Renters and auto specialist for Silicon Valley transplants.',
  '{"phone":"(650) 555-0171","email":"rent@svrenters.com","website":"https://www.svrenters.com","address":{"street":"4500 El Camino Real, Suite 200","city":"Los Altos","state":"CA","zip":"94022"}}'
),
(
  'a1000003-0003-4000-8000-000000000008',
  'riverside-inland-empire-insurance',
  'Riverside Inland Empire Insurance',
  'brokerage',
  ARRAY['homeowners', 'auto'],
  ARRAY['CA'],
  ARRAY['Riverside', 'Corona', 'Ontario'],
  '{"licenses":[{"state":"CA","license_number":"0L78901","type":"Property & Casualty","verification_url":"https://www.insurance.ca.gov/0200-industry/0070-check-license-status/"}]}',
  ARRAY['First-Time Homebuyers', 'Bundle Experts', 'Relocation Experienced'],
  4.2, 58, 11, TRUE, TRUE,
  'Riverside Inland Empire Insurance helps LA relocators and first-time buyers find affordable homeowners and auto coverage in the rapidly growing Inland Empire.',
  'Inland Empire brokerage for new homeowners and relocators.',
  '{"phone":"(951) 555-0126","email":"empire@riversideins.com","website":"https://www.riversideins.com","address":{"street":"3403 10th St, Suite 500","city":"Riverside","state":"CA","zip":"92501"}}'
),

-- New York (6 providers)
(
  'a1000004-0004-4000-8000-000000000001',
  'manhattan-premium-insurance',
  'Manhattan Premium Insurance',
  'brokerage',
  ARRAY['homeowners', 'renters', 'auto'],
  ARRAY['NY', 'NJ', 'CT'],
  ARRAY['New York', 'Manhattan', 'Brooklyn'],
  '{"licenses":[{"state":"NY","license_number":"BR-1234567","type":"Property & Casualty","verification_url":"https://myportal.dfs.ny.gov/web/guest-applications/check-license-status"},{"state":"NJ","license_number":"NJ-887766","type":"Property & Casualty","verification_url":"https://www.nj.gov/dobi/"}]}',
  ARRAY['High-Value Property', 'Co-op & Condo', 'Relocation Experienced'],
  4.8, 219, 30, TRUE, TRUE,
  'Manhattan Premium Insurance specializes in co-op, condo, and high-value renters policies for NYC professionals, with expertise in building requirements and liability limits.',
  'NYC brokerage for co-ops, condos, and high-value renters.',
  '{"phone":"(212) 555-0141","email":"premium@manhattanins.com","website":"https://www.manhattanins.com","address":{"street":"350 5th Ave, Suite 4200","city":"New York","state":"NY","zip":"10118"}}'
),
(
  'a1000004-0004-4000-8000-000000000002',
  'brooklyn-neighborhood-agents',
  'Brooklyn Neighborhood Agents',
  'independent_agent',
  ARRAY['renters', 'auto', 'homeowners'],
  ARRAY['NY'],
  ARRAY['Brooklyn', 'Queens'],
  '{"licenses":[{"state":"NY","license_number":"LA-2345678","type":"Property & Casualty","verification_url":"https://myportal.dfs.ny.gov/web/guest-applications/check-license-status"}]}',
  ARRAY['Renters Specialists', 'Bundle Experts', 'Small Business'],
  4.5, 103, 12, FALSE, TRUE,
  'Brooklyn Neighborhood Agents know every block—from brownstone renters in Park Slope to new homeowners in Bed-Stuy—with honest multi-carrier quotes.',
  'Brooklyn independent agent for renters and neighborhood coverage.',
  '{"phone":"(718) 555-0196","email":"hello@brooklynagents.com","website":"https://www.brooklynagents.com","address":{"street":"81 Willoughby St","city":"Brooklyn","state":"NY","zip":"11201"}}'
),
(
  'a1000004-0004-4000-8000-000000000003',
  'upstate-ny-medicare-solutions',
  'Upstate NY Medicare Solutions',
  'specialist',
  ARRAY['medicare', 'health'],
  ARRAY['NY'],
  ARRAY['Buffalo', 'Rochester', 'Syracuse'],
  '{"licenses":[{"state":"NY","license_number":"LA-3456789","type":"Health & Life","verification_url":"https://myportal.dfs.ny.gov/web/guest-applications/check-license-status"}]}',
  ARRAY['Medicare Specialists', 'Rural Health Plans', 'Senior Advocacy'],
  4.7, 145, 16, TRUE, TRUE,
  'Upstate NY Medicare Solutions serves seniors across Western and Central New York with personalized Medicare Advantage, Supplement, and Part D comparisons.',
  'Medicare specialist for Buffalo, Rochester, and Syracuse.',
  '{"phone":"(716) 555-0163","email":"medicare@upstateny.com","website":"https://www.upstateny.com","address":{"street":"726 Exchange St, Suite 300","city":"Buffalo","state":"NY","zip":"14210"}}'
),
(
  'a1000004-0004-4000-8000-000000000004',
  'long-island-family-insurance',
  'Long Island Family Insurance',
  'brokerage',
  ARRAY['homeowners', 'auto'],
  ARRAY['NY'],
  ARRAY['Hempstead', 'Garden City', 'Huntington'],
  '{"licenses":[{"state":"NY","license_number":"BR-4567890","type":"Property & Casualty","verification_url":"https://myportal.dfs.ny.gov/web/guest-applications/check-license-status"}]}',
  ARRAY['Flood Coverage', 'Bundle Experts', 'High-Value Property'],
  4.6, 128, 24, FALSE, TRUE,
  'Long Island Family Insurance protects Nassau and Suffolk county homes from coastal flood risks while delivering competitive auto bundles for suburban families.',
  'Long Island brokerage for flood, home, and auto coverage.',
  '{"phone":"(516) 555-0138","email":"family@liinsurance.com","website":"https://www.liinsurance.com","address":{"street":"1225 Franklin Ave, Suite 450","city":"Garden City","state":"NY","zip":"11530"}}'
),
(
  'a1000004-0004-4000-8000-000000000005',
  'albany-capital-region-insurance',
  'Albany Capital Region Insurance',
  'independent_agent',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['NY', 'VT', 'MA'],
  ARRAY['Albany', 'Schenectady', 'Troy'],
  '{"licenses":[{"state":"NY","license_number":"LA-5678901","type":"Property & Casualty","verification_url":"https://myportal.dfs.ny.gov/web/guest-applications/check-license-status"}]}',
  ARRAY['State Employee Plans', 'Bundle Experts', 'Relocation Experienced'],
  4.3, 72, 15, TRUE, TRUE,
  'Albany Capital Region Insurance serves government employees, university staff, and families across the Capital District with dependable property and auto coverage.',
  'Capital District agent for state employees and families.',
  '{"phone":"(518) 555-0182","email":"capital@albanyins.com","website":"https://www.albanyins.com","address":{"street":"80 State St, Suite 900","city":"Albany","state":"NY","zip":"12207"}}'
),
(
  'a1000004-0004-4000-8000-000000000006',
  'westchester-estate-insurance',
  'Westchester Estate Insurance',
  'specialist',
  ARRAY['homeowners'],
  ARRAY['NY', 'CT'],
  ARRAY['White Plains', 'Scarsdale', 'Yonkers'],
  '{"licenses":[{"state":"NY","license_number":"LA-6789012","type":"Property & Casualty","verification_url":"https://myportal.dfs.ny.gov/web/guest-applications/check-license-status"}]}',
  ARRAY['High-Value Property', 'Umbrella Liability', 'Historic Homes'],
  4.9, 95, 27, FALSE, TRUE,
  'Westchester Estate Insurance crafts tailored policies for historic homes, estate properties, and high-net-worth families throughout Westchester County.',
  'High-value homeowners specialist for Westchester estates.',
  '{"phone":"(914) 555-0157","email":"estates@westchesterins.com","website":"https://www.westchesterins.com","address":{"street":"1133 Westchester Ave, Suite 200","city":"White Plains","state":"NY","zip":"10604"}}'
),

-- North Carolina (5 providers)
(
  'a1000005-0005-4000-8000-000000000001',
  'charlotte-metro-insurance-partners',
  'Charlotte Metro Insurance Partners',
  'brokerage',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['NC', 'SC'],
  ARRAY['Charlotte', 'Matthews', 'Huntersville'],
  '{"licenses":[{"state":"NC","license_number":"NC-12345678","type":"Property & Casualty","verification_url":"https://www.ncdoi.gov/consumers/license-lookup"},{"state":"SC","license_number":"SC-998877","type":"Property & Casualty","verification_url":"https://www.doi.sc.gov/"}]}',
  ARRAY['Relocation Experienced', 'Bundle Experts', 'Banking Industry'],
  4.7, 176, 21, TRUE, TRUE,
  'Charlotte Metro Insurance Partners serves the nation''s second-largest banking hub with fast quotes for relocating professionals and longtime Carolina families.',
  'Charlotte brokerage for banking relocations and home bundles.',
  '{"phone":"(704) 555-0144","email":"partners@charlottemetro.com","website":"https://www.charlottemetro.com","address":{"street":"201 S Tryon St, Suite 1600","city":"Charlotte","state":"NC","zip":"28202"}}'
),
(
  'a1000005-0005-4000-8000-000000000002',
  'raleigh-triangle-insurance',
  'Raleigh Triangle Insurance',
  'independent_agent',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['NC'],
  ARRAY['Raleigh', 'Durham', 'Chapel Hill'],
  '{"licenses":[{"state":"NC","license_number":"NC-23456789","type":"Property & Casualty","verification_url":"https://www.ncdoi.gov/consumers/license-lookup"}]}',
  ARRAY['Tech Relocation', 'Bundle Experts', 'University Area'],
  4.6, 142, 13, TRUE, TRUE,
  'Raleigh Triangle Insurance helps Research Triangle transplants and UNC/Duke communities secure homeowners, renters, and auto coverage with local market knowledge.',
  'Triangle area agent for tech relocations and students.',
  '{"phone":"(919) 555-0190","email":"triangle@raleighins.com","website":"https://www.raleighins.com","address":{"street":"150 Fayetteville St, Suite 800","city":"Raleigh","state":"NC","zip":"27601"}}'
),
(
  'a1000005-0005-4000-8000-000000000003',
  'asheville-mountain-insurance',
  'Asheville Mountain Insurance',
  'independent_agent',
  ARRAY['homeowners', 'auto'],
  ARRAY['NC', 'TN', 'GA'],
  ARRAY['Asheville', 'Hendersonville'],
  '{"licenses":[{"state":"NC","license_number":"NC-34567890","type":"Property & Casualty","verification_url":"https://www.ncdoi.gov/consumers/license-lookup"}]}',
  ARRAY['Mountain Property', 'Vacation Homes', 'Relocation Experienced'],
  4.4, 68, 17, TRUE, TRUE,
  'Asheville Mountain Insurance understands mountain home risks, vacation properties, and the needs of remote workers relocating to Western North Carolina.',
  'Mountain home specialist for Asheville and WNC.',
  '{"phone":"(828) 555-0168","email":"mountain@ashevilleins.com","website":"https://www.ashevilleins.com","address":{"street":"29 Haywood St, Suite 200","city":"Asheville","state":"NC","zip":"28801"}}'
),
(
  'a1000005-0005-4000-8000-000000000004',
  'wilmington-coastal-insurance-nc',
  'Wilmington Coastal Insurance NC',
  'brokerage',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['NC'],
  ARRAY['Wilmington', 'Wrightsville Beach', 'Carolina Beach'],
  '{"licenses":[{"state":"NC","license_number":"NC-45678901","type":"Property & Casualty","verification_url":"https://www.ncdoi.gov/consumers/license-lookup"}]}',
  ARRAY['Coastal Coverage', 'Flood Insurance', 'Military Families'],
  4.5, 81, 14, TRUE, TRUE,
  'Wilmington Coastal Insurance NC provides hurricane-ready homeowners policies and flood coverage for Cape Fear coast residents and Camp Lejeune families.',
  'Coastal NC brokerage for flood and hurricane coverage.',
  '{"phone":"(910) 555-0135","email":"coastal@wilmingtonins.com","website":"https://www.wilmingtonins.com","address":{"street":"226 N Front St, Suite 400","city":"Wilmington","state":"NC","zip":"28401"}}'
),
(
  'a1000005-0005-4000-8000-000000000005',
  'greensboro-piedmont-health-advisors',
  'Greensboro Piedmont Health Advisors',
  'specialist',
  ARRAY['health', 'medicare'],
  ARRAY['NC', 'VA'],
  ARRAY['Greensboro', 'Winston-Salem', 'High Point'],
  '{"licenses":[{"state":"NC","license_number":"NC-56789012","type":"Health & Life","verification_url":"https://www.ncdoi.gov/consumers/license-lookup"}]}',
  ARRAY['Medicare Specialists', 'ACA Marketplace', 'Small Business Health'],
  4.3, 59, 11, FALSE, TRUE,
  'Greensboro Piedmont Health Advisors guides Triad families through ACA enrollment, Medicare transitions, and small business group health plan selection.',
  'Health and Medicare advisor for Greensboro Triad region.',
  '{"phone":"(336) 555-0179","email":"health@piedmontadvisors.com","website":"https://www.piedmontadvisors.com","address":{"street":"324 W Wendover Ave, Suite 200","city":"Greensboro","state":"NC","zip":"27401"}}'
),

-- Illinois (5 providers)
(
  'a1000006-0006-4000-8000-000000000001',
  'chicago-lakeshore-insurance',
  'Chicago Lakeshore Insurance',
  'brokerage',
  ARRAY['homeowners', 'renters', 'auto'],
  ARRAY['IL', 'IN', 'WI'],
  ARRAY['Chicago', 'Evanston', 'Oak Park'],
  '{"licenses":[{"state":"IL","license_number":"12345678","type":"Property & Casualty","verification_url":"https://www.insurance.illinois.gov/Producer/ProducerList"},{"state":"IN","license_number":"IN-445566","type":"Property & Casualty","verification_url":"https://www.in.gov/idoi/"}]}',
  ARRAY['Condo & Co-op', 'Bundle Experts', 'Relocation Experienced'],
  4.7, 191, 29, TRUE, TRUE,
  'Chicago Lakeshore Insurance protects lakefront condos, urban renters, and suburban homeowners across Chicagoland with multi-carrier expertise and winter weather know-how.',
  'Chicagoland brokerage for condos, renters, and relocations.',
  '{"phone":"(312) 555-0147","email":"lakeshore@chicago-ins.com","website":"https://www.chicago-ins.com","address":{"street":"233 S Wacker Dr, Suite 8400","city":"Chicago","state":"IL","zip":"60606"}}'
),
(
  'a1000006-0006-4000-8000-000000000002',
  'naperville-suburban-insurance',
  'Naperville Suburban Insurance',
  'independent_agent',
  ARRAY['homeowners', 'auto'],
  ARRAY['IL'],
  ARRAY['Naperville', 'Aurora', 'Wheaton'],
  '{"licenses":[{"state":"IL","license_number":"23456789","type":"Property & Casualty","verification_url":"https://www.insurance.illinois.gov/Producer/ProducerList"}]}',
  ARRAY['Family Coverage', 'Bundle Experts', 'Youth Driver Programs'],
  4.5, 108, 16, FALSE, TRUE,
  'Naperville Suburban Insurance serves DuPage County families with competitive homeowners and auto bundles, including teen driver education discounts.',
  'DuPage County agent for family home and auto bundles.',
  '{"phone":"(630) 555-0194","email":"suburban@napervilleins.com","website":"https://www.napervilleins.com","address":{"street":"55 E Jefferson Ave, Suite 200","city":"Naperville","state":"IL","zip":"60540"}}'
),
(
  'a1000006-0006-4000-8000-000000000003',
  'springfield-illinois-medicare',
  'Springfield Illinois Medicare',
  'specialist',
  ARRAY['medicare', 'health'],
  ARRAY['IL'],
  ARRAY['Springfield', 'Decatur', 'Champaign'],
  '{"licenses":[{"state":"IL","license_number":"34567890","type":"Health & Life","verification_url":"https://www.insurance.illinois.gov/Producer/ProducerList"}]}',
  ARRAY['Medicare Specialists', 'Rural Health', 'State Retiree Plans'],
  4.6, 88, 19, TRUE, TRUE,
  'Springfield Illinois Medicare helps state retirees and central Illinois seniors navigate Medicare enrollment, supplements, and prescription drug plans.',
  'Medicare specialist for Springfield and central Illinois.',
  '{"phone":"(217) 555-0161","email":"medicare@springfieldil.com","website":"https://www.springfieldil.com","address":{"street":"528 S 5th St, Suite 300","city":"Springfield","state":"IL","zip":"62701"}}'
),
(
  'a1000006-0006-4000-8000-000000000004',
  'rockford-northern-illinois-agents',
  'Rockford Northern Illinois Agents',
  'independent_agent',
  ARRAY['auto', 'homeowners', 'renters'],
  ARRAY['IL', 'WI'],
  ARRAY['Rockford', 'Belvidere'],
  '{"licenses":[{"state":"IL","license_number":"45678901","type":"Property & Casualty","verification_url":"https://www.insurance.illinois.gov/Producer/ProducerList"}]}',
  ARRAY['Bundle Experts', 'Manufacturing Workers'],
  3.8, 34, 10, FALSE, TRUE,
  'Rockford Northern Illinois Agents provide no-frills auto and property insurance for factory workers, small business owners, and families in the Rock River valley.',
  'Affordable coverage for Rockford and northern Illinois.',
  '{"phone":"(815) 555-0133","email":"agents@rockfordins.com","website":"https://www.rockfordins.com","address":{"street":"100 W State St, Suite 400","city":"Rockford","state":"IL","zip":"61101"}}'
),
(
  'a1000006-0006-4000-8000-000000000005',
  'peoria-heartland-insurance',
  'Peoria Heartland Insurance',
  'brokerage',
  ARRAY['homeowners', 'auto', 'health'],
  ARRAY['IL', 'IA', 'MO'],
  ARRAY['Peoria', 'Bloomington', 'Normal'],
  '{"licenses":[{"state":"IL","license_number":"56789012","type":"Property & Casualty","verification_url":"https://www.insurance.illinois.gov/Producer/ProducerList"}]}',
  ARRAY['Bundle Experts', 'Caterpillar Employees', 'Relocation Experienced'],
  4.4, 77, 20, TRUE, TRUE,
  'Peoria Heartland Insurance serves manufacturing families, healthcare workers, and Illinois State University communities with integrated property, auto, and health solutions.',
  'Central Illinois brokerage for manufacturing and university families.',
  '{"phone":"(309) 555-0180","email":"heartland@peoriains.com","website":"https://www.peoriains.com","address":{"street":"456 Fulton St, Suite 300","city":"Peoria","state":"IL","zip":"61602"}}'
),

-- Additional States (10 providers)
(
  'a1000007-0007-4000-8000-000000000001',
  'phoenix-desert-shield-insurance',
  'Phoenix Desert Shield Insurance',
  'brokerage',
  ARRAY['homeowners', 'auto'],
  ARRAY['AZ', 'NV'],
  ARRAY['Phoenix', 'Scottsdale', 'Mesa'],
  '{"licenses":[{"state":"AZ","license_number":"AZ-123456","type":"Property & Casualty","verification_url":"https://insurance.az.gov/licenses"},{"state":"NV","license_number":"NV-778899","type":"Property & Casualty","verification_url":"https://doi.nv.gov/"}]}',
  ARRAY['Pool & Spa Liability', 'Relocation Experienced', 'Snowbird Coverage'],
  4.6, 165, 18, TRUE, TRUE,
  'Phoenix Desert Shield Insurance helps newcomers and snowbirds secure homeowners and auto coverage designed for desert climates, pools, and monsoon season risks.',
  'Phoenix brokerage for desert homes and snowbird coverage.',
  '{"phone":"(602) 555-0149","email":"desert@phoenixshield.com","website":"https://www.phoenixshield.com","address":{"street":"2 N Central Ave, Suite 1800","city":"Phoenix","state":"AZ","zip":"85004"}}'
),
(
  'a1000007-0007-4000-8000-000000000002',
  'denver-mile-high-insurance',
  'Denver Mile High Insurance',
  'independent_agent',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['CO', 'WY'],
  ARRAY['Denver', 'Boulder', 'Aurora'],
  '{"licenses":[{"state":"CO","license_number":"CO-456789","type":"Property & Casualty","verification_url":"https://doi.colorado.gov/"}]}',
  ARRAY['Wildfire Mitigation', 'Bundle Experts', 'Outdoor Recreation'],
  4.5, 119, 14, TRUE, TRUE,
  'Denver Mile High Insurance covers mountain-adjacent homes, outdoor enthusiasts, and Front Range renters with wildfire-aware policies and competitive auto rates.',
  'Denver agent for wildfire-aware home and auto coverage.',
  '{"phone":"(303) 555-0192","email":"milehigh@denverins.com","website":"https://www.denverins.com","address":{"street":"1700 Lincoln St, Suite 2400","city":"Denver","state":"CO","zip":"80203"}}'
),
(
  'a1000007-0007-4000-8000-000000000003',
  'atlanta-peachtree-insurance-group',
  'Atlanta Peachtree Insurance Group',
  'brokerage',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['GA', 'AL', 'TN'],
  ARRAY['Atlanta', 'Marietta', 'Alpharetta'],
  '{"licenses":[{"state":"GA","license_number":"GA-987654","type":"Property & Casualty","verification_url":"https://oci.georgia.gov/verify-license"}]}',
  ARRAY['Corporate Relocation', 'Bundle Experts', 'Hail Damage'],
  4.7, 184, 25, TRUE, TRUE,
  'Atlanta Peachtree Insurance Group is a leading brokerage for Fortune 500 relocations, suburban homeowners, and apartment renters across Metro Atlanta.',
  'Atlanta brokerage for corporate relocations and hail coverage.',
  '{"phone":"(404) 555-0164","email":"peachtree@atlantains.com","website":"https://www.atlantains.com","address":{"street":"191 Peachtree St NE, Suite 3500","city":"Atlanta","state":"GA","zip":"30303"}}'
),
(
  'a1000007-0007-4000-8000-000000000004',
  'seattle-pacific-northwest-insurance',
  'Seattle Pacific Northwest Insurance',
  'brokerage',
  ARRAY['homeowners', 'renters', 'auto'],
  ARRAY['WA', 'OR', 'ID'],
  ARRAY['Seattle', 'Bellevue', 'Tacoma'],
  '{"licenses":[{"state":"WA","license_number":"WA-112233","type":"Property & Casualty","verification_url":"https://www.insurance.wa.gov/"},{"state":"OR","license_number":"OR-445566","type":"Property & Casualty","verification_url":"https://dfr.oregon.gov/"}]}',
  ARRAY['Earthquake Coverage', 'Tech Relocation', 'Watercraft'],
  4.8, 207, 22, TRUE, TRUE,
  'Seattle Pacific Northwest Insurance provides earthquake endorsements, tech-worker renters policies, and boat coverage for Puget Sound residents and transplants.',
  'Seattle brokerage for earthquake, tech, and watercraft coverage.',
  '{"phone":"(206) 555-0139","email":"pnw@seattleins.com","website":"https://www.seattleins.com","address":{"street":"999 3rd Ave, Suite 3300","city":"Seattle","state":"WA","zip":"98104"}}'
),
(
  'a1000007-0007-4000-8000-000000000005',
  'richmond-virginia-heritage-insurance',
  'Richmond Virginia Heritage Insurance',
  'independent_agent',
  ARRAY['homeowners', 'auto'],
  ARRAY['VA', 'MD', 'NC'],
  ARRAY['Richmond', 'Henrico', 'Chesterfield'],
  '{"licenses":[{"state":"VA","license_number":"VA-334455","type":"Property & Casualty","verification_url":"https://www.scc.virginia.gov/pages/Bureau-of-Insurance"}]}',
  ARRAY['Historic Homes', 'Bundle Experts', 'Government Employees'],
  4.4, 86, 19, FALSE, TRUE,
  'Richmond Virginia Heritage Insurance protects historic properties and modern suburban homes while serving state government employees throughout the capital region.',
  'Richmond agent for historic homes and government employees.',
  '{"phone":"(804) 555-0177","email":"heritage@richmondins.com","website":"https://www.richmondins.com","address":{"street":"919 E Main St, Suite 400","city":"Richmond","state":"VA","zip":"23219"}}'
),
(
  'a1000007-0007-4000-8000-000000000006',
  'philadelphia-liberty-insurance-brokers',
  'Philadelphia Liberty Insurance Brokers',
  'brokerage',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['PA', 'NJ', 'DE'],
  ARRAY['Philadelphia', 'King of Prussia', 'Media'],
  '{"licenses":[{"state":"PA","license_number":"PA-556677","type":"Property & Casualty","verification_url":"https://www.insurance.pa.gov/"},{"state":"NJ","license_number":"NJ-112233","type":"Property & Casualty","verification_url":"https://www.nj.gov/dobi/"}]}',
  ARRAY['Rowhome Coverage', 'Bundle Experts', 'Relocation Experienced'],
  4.5, 121, 23, TRUE, TRUE,
  'Philadelphia Liberty Insurance Brokers understand rowhome quirks, suburban Main Line estates, and the insurance needs of tri-state area relocators.',
  'Philadelphia brokerage for rowhomes and tri-state coverage.',
  '{"phone":"(215) 555-0151","email":"liberty@phillyins.com","website":"https://www.phillyins.com","address":{"street":"1601 Market St, Suite 2500","city":"Philadelphia","state":"PA","zip":"19103"}}'
),
(
  'a1000007-0007-4000-8000-000000000007',
  'columbus-ohio-insurance-partners',
  'Columbus Ohio Insurance Partners',
  'independent_agent',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['OH'],
  ARRAY['Columbus', 'Dublin', 'Westerville'],
  '{"licenses":[{"state":"OH","license_number":"OH-667788","type":"Property & Casualty","verification_url":"https://insurance.ohio.gov/"}]}',
  ARRAY['Bundle Experts', 'University Area', 'First-Time Homebuyers'],
  4.3, 74, 12, TRUE, TRUE,
  'Columbus Ohio Insurance Partners helps OSU students, young professionals, and growing families find affordable renters, auto, and homeowners coverage in Central Ohio.',
  'Columbus agent for students, families, and first-time buyers.',
  '{"phone":"(614) 555-0185","email":"partners@columbusins.com","website":"https://www.columbusins.com","address":{"street":"250 W Street St, Suite 500","city":"Columbus","state":"OH","zip":"43215"}}'
),
(
  'a1000007-0007-4000-8000-000000000008',
  'newark-garden-state-insurance',
  'Newark Garden State Insurance',
  'brokerage',
  ARRAY['auto', 'homeowners', 'renters'],
  ARRAY['NJ', 'NY', 'PA'],
  ARRAY['Newark', 'Jersey City', 'Hoboken'],
  '{"licenses":[{"state":"NJ","license_number":"NJ-998877","type":"Property & Casualty","verification_url":"https://www.nj.gov/dobi/"}]}',
  ARRAY['Commuter Coverage', 'High-Rise Renters', 'Relocation Experienced'],
  4.2, 63, 15, TRUE, TRUE,
  'Newark Garden State Insurance specializes in NYC commuter auto policies, high-rise renters coverage, and urban homeowners insurance across northern New Jersey.',
  'NJ brokerage for commuters, renters, and urban homeowners.',
  '{"phone":"(973) 555-0129","email":"garden@njinsurance.com","website":"https://www.njinsurance.com","address":{"street":"One Gateway Center, Suite 2600","city":"Newark","state":"NJ","zip":"07102"}}'
),
(
  'a1000007-0007-4000-8000-000000000009',
  'nashville-music-city-insurance',
  'Nashville Music City Insurance',
  'independent_agent',
  ARRAY['homeowners', 'auto', 'renters'],
  ARRAY['TN', 'KY'],
  ARRAY['Nashville', 'Franklin', 'Murfreesboro'],
  '{"licenses":[{"state":"TN","license_number":"TN-223344","type":"Property & Casualty","verification_url":"https://www.tn.gov/commerce/insurance.html"}]}',
  ARRAY['Entertainment Industry', 'Bundle Experts', 'Rapid Growth Markets'],
  4.6, 137, 11, TRUE, TRUE,
  'Nashville Music City Insurance covers the city''s explosive growth with policies for musicians, entertainment professionals, and families in booming suburbs.',
  'Nashville agent for entertainment pros and growing suburbs.',
  '{"phone":"(615) 555-0166","email":"music@nashvilleins.com","website":"https://www.nashvilleins.com","address":{"street":"501 Union St, Suite 400","city":"Nashville","state":"TN","zip":"37219"}}'
),
(
  'a1000007-0007-4000-8000-000000000010',
  'portland-rose-city-insurance',
  'Portland Rose City Insurance',
  'brokerage',
  ARRAY['homeowners', 'renters', 'auto'],
  ARRAY['OR', 'WA'],
  ARRAY['Portland', 'Beaverton', 'Lake Oswego'],
  '{"licenses":[{"state":"OR","license_number":"OR-778899","type":"Property & Casualty","verification_url":"https://dfr.oregon.gov/"}]}',
  ARRAY['Earthquake Coverage', 'Eco-Friendly Homes', 'Bundle Experts'],
  4.4, 82, 16, FALSE, TRUE,
  'Portland Rose City Insurance offers earthquake riders, green home discounts, and comprehensive bundles for Pacific Northwest urban and suburban residents.',
  'Portland brokerage for earthquake and eco-friendly coverage.',
  '{"phone":"(503) 555-0143","email":"rose@portlandins.com","website":"https://www.portlandins.com","address":{"street":"121 SW Salmon St, Suite 1100","city":"Portland","state":"OR","zip":"97204"}}'
);

-- Sample pending review (demonstrates public insert workflow; admin approval triggers rating recalc)
INSERT INTO reviews (provider_id, author_name, author_location, rating, title, content, status) VALUES
('a1000002-0002-4000-8000-000000000003', 'Jennifer Adams', 'Dallas, TX', 4, 'Very professional team', 'Still waiting for final quote but initial consultation was thorough and helpful.', 'pending');

-- Sample leads
INSERT INTO leads (provider_id, name, email, phone, message, insurance_types, destination, source) VALUES
(NULL, 'Thomas Wright', 'thomas.wright@email.com', '(555) 234-5678', 'Moving from Boston to Austin in September. Need homeowners and auto quotes.', ARRAY['homeowners', 'auto'], 'Austin, TX', 'relocation-quiz'),
('a1000002-0002-4000-8000-000000000002', 'Amanda Foster', 'amanda.f@email.com', '(555) 345-6789', 'Looking for renters insurance near downtown Austin.', ARRAY['renters'], 'Austin, TX', 'provider-profile'),
(NULL, 'Carlos Mendez', 'carlos.m@email.com', NULL, 'Need Medicare guidance for my parents relocating to Florida.', ARRAY['medicare'], 'West Palm Beach, FL', 'contact-form');