import type { Metadata } from 'next';
import Link from 'next/link';
import { buildMetadata } from '@/lib/seo/metadata';
import snapshot from '@/lib/indiana-intelligence/accepted-snapshot.json';

export const metadata: Metadata = buildMetadata({
  title: 'Indiana insurance licensing and IDOI regulatory evidence',
  description: 'Indiana IDOI company and producer verification, bounded administrative-action index, domestic financial examinations, market conduct and complaint capabilities.',
  path: '/indiana',
});

const official = (href: string, label: string) => <a className="font-medium text-sky-700 underline underline-offset-2" href={href} target="_blank" rel="noopener noreferrer">{label}</a>;
const fmt = (value: number) => value.toLocaleString('en-US');
const producerLookup = 'https://www.in.gov/idoi/licensing/';
const marketConduct = 'https://www.in.gov/idoi/enforcement/market-conduct/';
const complaints = 'https://www.in.gov/idoi/consumer-services/information/';
const fraud = 'https://www.in.gov/idoi/enforcement/fraud-reporting/';

export default function IndianaInsurancePage() {
  return <main className="th-shell mx-auto w-full max-w-[960px] overflow-x-clip px-4 py-8 sm:py-10">
    <nav aria-label="Breadcrumb" className="mb-4 text-sm"><Link href="/" className="text-sky-700 underline">Home</Link><span aria-hidden="true"> / </span>Indiana research</nav>
    <header><p className="text-xs font-semibold uppercase tracking-wider text-sky-700">Indiana Department of Insurance · IDOI</p><h1 className="mt-2 text-3xl font-bold text-[#0A2540]">Indiana insurance licensing and regulatory records</h1><p className="mt-3 max-w-3xl text-slate-700">IDOI regulates legal insurance companies and licenses producer businesses and people. Its enforcement orders, examinations and complaints are separate evidence, not a combined business count or quality score.</p></header>

    <section aria-label="Indiana evidence summary" className="mt-8 grid gap-3 sm:grid-cols-3">
      <div className="rounded-xl border border-slate-200 bg-white p-5"><strong className="text-3xl text-[#0A2540]">{fmt(snapshot.enforcement.rowCount)}</strong><p className="mt-1 text-sm">IDOI enforcement-action table rows dated 2022 through September 29, 2026; mixed company, agency, person and applicant grains</p></div>
      <div className="rounded-xl border border-slate-200 bg-white p-5"><strong className="text-3xl text-[#0A2540]">{fmt(snapshot.financialExams.indexRows)}</strong><p className="mt-1 text-sm">Domestic financial-exam report-year links; {snapshot.financialExams.recent2022to2026} dated 2022–2026</p></div>
      <div className="rounded-xl border border-slate-200 bg-white p-5"><strong className="text-lg text-[#0A2540]">NOT_ACQUIRED</strong><p className="mt-1 text-sm">Statewide current legal-insurer roster and company count. IDOI offers company verification.</p></div>
    </section>

    <section className="mt-10 space-y-3 text-sm leading-relaxed text-slate-700"><h2 className="text-2xl font-semibold text-[#0A2540]">Company, agency and producer verification</h2><p>IDOI’s {official(snapshot.companyRoster.source, 'company lists by type')} describe licensed, registered, surplus-lines and reinsurance categories and direct consumers to Sircon company inquiry. These categories do not form one insurer census. A current company-level roster with NAIC, status, domicile and authority was NOT_ACQUIRED; company rows, distinct company NAIC codes and exact canonical company matches remain unknown.</p><p>IDOI’s {official(producerLookup, 'licensing page')} provides agent and agency verification through Sircon or NIPR. Agency, individual-producer and appointment bulk rosters were NOT_ACQUIRED. An NPN can refer to a person or business entity; verify that grain before using it. No person record was promoted to a company profile.</p></section>

    <section className="mt-10 space-y-3 text-sm leading-relaxed text-slate-700"><h2 className="text-2xl font-semibold text-[#0A2540]">Enforcement actions</h2><p>The {official(snapshot.enforcement.source, 'IDOI enforcement-action table')} supplies {fmt(snapshot.enforcement.rowCount)} rows in the bounded 2022–2026 window. Each frozen row retains respondent, printed administrative-action description, final-order date, action wording, order number, printed license/NPN and source document where linked. Table entries include individuals, applicants, agencies and companies; an application denial is not a revocation of an active company license. Read the order for procedural meaning. No adverse order was attached to a canonical profile by name: exact adverse attachments 0; name-only adverse joins 0.</p><div className="overflow-x-auto"><table className="w-full min-w-[540px] text-left"><caption className="mb-2 text-left font-semibold">Recent IDOI order-index examples</caption><thead><tr><th className="py-2">Respondent as printed</th><th>Date</th><th>Action as printed</th><th>Order</th></tr></thead><tbody>{snapshot.enforcement.rows.slice(-5).map((row, index) => <tr className="border-t border-slate-200" key={`${row.orderNumber}-${index}`}><td className="py-2 pr-2">{row.respondent}</td><td className="pr-2 whitespace-nowrap">{row.finalOrderDate}</td><td className="pr-2">{row.actionAsPrinted}</td><td>{row.sourceDocument ? official(row.sourceDocument, row.orderNumber) : row.orderNumber}</td></tr>)}</tbody></table></div></section>

    <section className="mt-10 space-y-3 text-sm leading-relaxed text-slate-700"><h2 className="text-2xl font-semibold text-[#0A2540]">Market conduct and financial examinations</h2><p>IDOI {official(marketConduct, 'conducts market-conduct examinations')} and says adopted reports and related final orders may be found through enforcement actions. A clean standalone statewide 2022–2026 market-conduct report index was NOT_ACQUIRED. This does not mean no exams occurred; an exam is not automatically an adverse action.</p><p>The {official(snapshot.financialExams.source, 'IDOI domestic financial-exam table')} has {fmt(snapshot.financialExams.indexRows)} report-year links across {snapshot.financialExams.distinctNaic} printed NAIC codes; {snapshot.financialExams.recent2022to2026} links are dated 2022–2026. Exactly {snapshot.financialExams.exactExistingCanonicalNaicOverlap} of those NAIC codes overlap existing canonical legal-insurer identity codes, while {snapshot.financialExams.unmatchedNaic} do not. These are read-only exact identifier intersections from an exam index, not proof of current Indiana authority or profile-level exam attachments. No name-only exam join was made.</p></section>

    <section className="mt-10 space-y-3 text-sm leading-relaxed text-slate-700"><h2 className="text-2xl font-semibold text-[#0A2540]">Complaints, fraud and coverage limits</h2><p>IDOI {official(complaints, 'accepts consumer insurance complaints')} and provides a separate {official(fraud, 'fraud-reporting path')}. Intake is KNOWN; provider-level complaint cases and outcomes are NOT_ACQUIRED. A complaint or fraud report is not an enforcement finding.</p><ul className="list-disc space-y-1 pl-5"><li>Company and agency/producer statewide rosters: NOT_ACQUIRED. Missing does not mean zero.</li><li>Market-conduct standalone exam index and provider complaint outcomes: NOT_ACQUIRED.</li><li>New canonical organizations: {snapshot.graph.newCanonicalOrganizations}; graph writes: {snapshot.graph.graphWrites}; claim eligibility changes: {snapshot.graph.claimEligibilityChanges}.</li><li>IDOI source pages retrieved {snapshot.retrievedAt}; enforcement rows keep their own final-order dates, financial reports keep printed report years, and this snapshot was generated {snapshot.generatedAt}. There is no universal Indiana as-of date.</li><li>Indianapolis, Fort Wayne, Evansville and South Bend are search context only. No city or county pages are published.</li></ul></section>
  </main>;
}
