import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { interpretInsuranceAskQuery } from '../lib/insurance-ask/interpret';
import { STATE_RESEARCH } from '../lib/insurance-ask/recovery';
import { normalizedPublishedStatePath } from '../lib/seo/published-state-path';

const read = (p: string) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const snapshot = JSON.parse(read('lib/idaho-intelligence/id-ins-001.json'));
const page = read('app/idaho/page.tsx');
const sitemap = read('app/sitemap.ts');
const ask = (q: string) => interpretInsuranceAskQuery(q).query.failReason ?? '';

const licensed = Object.values(snapshot.licensed) as number[];
const listed = Object.values(snapshot.listed) as number[];
const registered = Object.values(snapshot.registered) as number[];
const other = Object.values(snapshot.otherRegulatedEntities) as number[];
const classSum = [...licensed, ...listed, ...registered, ...other].reduce((sum, value) => sum + value, 0);

assert.equal(snapshot.regulator, 'Idaho Department of Insurance');
assert.equal(snapshot.annualStatementClock, '2024-12-31');
assert.equal(snapshot.letterDate, '2025-11-01');
assert.equal(snapshot.licenseStockAsOf, 'NOT_PRINTED');
assert.equal(snapshot.sha256, '4e2b35d7e3fb204c75bcc5b2c230dee8b6aebcb2bf8bc4ef2684394f3765e67e');
assert.equal(snapshot.bytes, 19223231);
assert.equal(classSum, 2384);
assert.equal(snapshot.totalCompaniesRegulatedEntities, 2384);
assert.equal(snapshot.totalIsReportPrinted, true);
assert.equal(snapshot.classesAddedByThisPage, false);
assert.equal(snapshot.licensed.hospitalLiabilitiesTrusts, 0);
assert.equal(snapshot.licensed.propertyAndCasualty, 875);
assert.equal(snapshot.licensed.title, 19);
assert.equal(snapshot.listed.surplusLines, 207);
assert.equal(snapshot.licensesMaintained, 114549);
assert.equal(snapshot.personVsBusiness, 'NOT_SEPARATED');
assert.equal(snapshot.residentVsNonresident, 'NOT_SEPARATED');
assert.equal(snapshot.licensesAddedToRegulatedEntities, false);
assert.notEqual(snapshot.licensesMaintained, snapshot.totalCompaniesRegulatedEntities);
assert.equal(snapshot.combinedInsurancePopulation, null);
assert.equal(snapshot.newLicenses2024.addedToLicensesMaintained, false);
assert.equal(snapshot.newLicenses2024.rowTotalPublished, false);
assert.equal(snapshot.newLicenses2024.individual.length, 6);
assert.equal(snapshot.newLicenses2024.business.length, 6);
assert.equal(snapshot.orders.producers.licenseRevoked, 52);
assert.equal(snapshot.orders.ordersAreNotPopulations, true);
assert.equal(snapshot.orders.otherTitleAgenciesTpasRrgs.combinedActionLineIsNotSplit, true);
assert.equal(snapshot.complaints.areFindings, false);
assert.equal(snapshot.complaints.sameRows, false);
assert.equal(snapshot.examinations.areCompanyCounts, false);
assert.equal(snapshot.continuingEducationCoursesAreLicensees, false);
assert.equal(snapshot.serff.filingsAreLicensees, false);
assert.equal(snapshot.appointmentIsLicense, false);
assert.equal(snapshot.sbsLookupIsBulkCensus, false);
assert.equal(snapshot.notAcquired.sbsBulkExport, 'NOT_ACQUIRED');
assert.equal(snapshot.notAcquired.adjusterRoster, 'NOT_ACQUIRED');
assert.equal(snapshot.notAcquired.appointmentRoster, 'NOT_ACQUIRED');
assert.equal(snapshot.nameOnlyAdverseJoins, 0);
assert.equal(snapshot.graphWrites, 0);
assert.equal(snapshot.netNewEntities, 0);
assert.equal(snapshot.aggregateRating, null);
assert.equal(snapshot.trustScore, null);
assert.equal(STATE_RESEARCH.ID, '/idaho');
assert.equal(normalizedPublishedStatePath('/Idaho'), '/idaho');
assert.equal(normalizedPublishedStatePath('/idaho'), null);
assert.equal(normalizedPublishedStatePath('/idaho/boise'), null);
assert.equal((sitemap.match(/'\/idaho'/g) ?? []).length, 1);
assert.equal((sitemap.match(/'\/kansas'/g) ?? []).length, 1);
assert.equal((sitemap.match(/'\/new-mexico'/g) ?? []).length, 1);
assert.deepEqual(readdirSync(new URL('../app/idaho', import.meta.url)), ['page.tsx']);
assert.match(page, /path: '\/idaho'/);
assert.match(page, /personVsBusiness/);
assert.match(page, /does not split the license stock/);
assert.match(page, /not added/);
assert.match(page, /does not print a sum/);
assert.match(page, /not a finding/);
assert.match(page, /not a license/);
assert.match(page, /geography only/);
assert.match(page, /not a producer count/);
assert.doesNotMatch(page, /AggregateRating|ratingValue|Trust Score/);
assert.doesNotMatch(page, /116,?933|54,?403|2,?931/);
assert.doesNotMatch(page, /\/idaho\/boise/);

for (const q of ['how many insurers in Idaho', 'insurance companies in id', 'Idaho insurance']) {
  assert.match(ask(q), /2,384/, q);
  assert.match(ask(q), /not a producer count/, q);
  assert.match(ask(q), /114,549/, q);
}
for (const q of ['id', 'ID', 'mover id', 'insurance id', 'best insurer ID']) {
  assert.doesNotMatch(ask(q), /Idaho Department of Insurance/, q);
}
assert.match(ask('how many producers in Idaho'), /NOT_SEPARATED/);
assert.match(ask('how many producers in Idaho'), /not added/);
assert.match(ask('Idaho adjusters'), /NOT_ACQUIRED/);
assert.match(ask('Idaho appointments'), /not a license/);
assert.match(ask('Idaho surplus lines'), /207/);
assert.match(ask('Idaho surplus lines'), /not added/);
assert.match(ask('Idaho title insurance'), /19/);
assert.match(ask('Idaho title examinations'), /not the 19/);
assert.match(ask('Idaho complaints'), /not a finding/);
assert.match(ask('best Idaho insurer'), /does not rank/);
assert.match(ask('insurance Boise Idaho'), /geography only/);
assert.match(ask('insurance Boise'), /geography only/);
assert.doesNotMatch(ask('Boise'), /Idaho Department of Insurance/);
assert.match(ask('New Mexico title insurance'), /68/);
assert.doesNotMatch(ask('New Mexico title insurance'), /Idaho Department of Insurance/);
assert.match(ask('Nebraska insurers'), /1,687/);
assert.doesNotMatch(ask('Nebraska insurers'), /Idaho Department of Insurance/);
