import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ILLINOIS_INTELLIGENCE_GATE, CANONICAL_IL_SNAPSHOT_FINGERPRINT } from '../lib/illinois-intelligence/publication';
import { assertIllinoisInsurance } from '../lib/illinois-intelligence/snapshot';
import { buildIllinoisInsuranceJsonLd, ilJsonLdHasForbiddenRatings } from '../lib/illinois-intelligence/jsonld';
import { interpretInsuranceAskQuery } from '../lib/insurance-ask/interpret';

const root = process.cwd();
const snap = assertIllinoisInsurance();
const sitemap = readFileSync(join(root, 'app/sitemap.ts'), 'utf8');
const footer = readFileSync(join(root, 'lib/design/insurance-design-system.ts'), 'utf8');
const ui = readFileSync(join(root, 'components/illinois/il-state-page.tsx'), 'utf8');
const page = readFileSync(join(root, 'app/illinois/page.tsx'), 'utf8');
const pkg = readFileSync(join(root, 'package.json'), 'utf8');
const interpret = readFileSync(join(root, 'lib/insurance-ask/interpret.ts'), 'utf8');
const golden = readFileSync(join(root, 'lib/specialist-search/golden-questions.ts'), 'utf8');

if (!existsSync(join(root, 'app/illinois/page.tsx'))) throw new Error('missing /illinois');
if (snap.fingerprint !== CANONICAL_IL_SNAPSHOT_FINGERPRINT) throw new Error('fingerprint gate');
if (ILLINOIS_INTELLIGENCE_GATE.path !== '/illinois') throw new Error('path');
if (ILLINOIS_INTELLIGENCE_GATE.robotsIndex !== true) throw new Error('index');
if (!sitemap.includes("'/illinois'")) throw new Error('sitemap');
if (sitemap.includes("'/illinois/")) throw new Error('nested illinois sitemap');
if (!footer.includes('/illinois')) throw new Error('footer');
if (!pkg.includes('assert:il-ins-001')) throw new Error('package script');
if (ui.includes('/illinois/chicago') || ui.includes('/illinois/cook')) throw new Error('local routes');
if (!ui.toLowerCase().includes('trust score')) throw new Error('trust score guard');
if (ui.match(/best insurer|worst insurer|safest/i)) throw new Error('ranking language');
if (page.includes('aggregateRating')) throw new Error('schema rating');
if (ilJsonLdHasForbiddenRatings(buildIllinoisInsuranceJsonLd(snap))) throw new Error('jsonld rating');
if (snap.directors_orders.observation_rows !== 2896) throw new Error('2896');
if (snap.company_lookup.count != null) throw new Error('company count');
if (!interpret.includes('illinois')) throw new Error('ask illinois');
if (!golden.includes('licensed insurance agencies in Illinois')) throw new Error('golden IL agency');
if (!golden.includes('Illinois insurance agents')) throw new Error('golden IL producer');
if (!golden.includes('licensed insurance companies in Illinois')) throw new Error('golden IL companies');
if (!existsSync(join(root, 'app/new-york/page.tsx'))) throw new Error('New York route missing');
if (!existsSync(join(root, 'app/virginia/page.tsx'))) throw new Error('Virginia route missing');
if (!existsSync(join(root, 'app/colorado/page.tsx'))) throw new Error('Colorado route missing');

const licensed = interpretInsuranceAskQuery('How many insurance companies are licensed in Illinois?');
if (licensed.query.mode !== 'fail_closed') throw new Error('licensed companies must fail closed');
const agencies = interpretInsuranceAskQuery('insurance agencies in Illinois');
if (agencies.query.mode !== 'fail_closed') throw new Error('agencies must fail closed');
const agents = interpretInsuranceAskQuery('insurance agents in Illinois');
if (agents.query.mode !== 'fail_closed') throw new Error('agents must fail closed');
const complaints = interpretInsuranceAskQuery('complaints against an insurer in Illinois');
if (complaints.query.mode !== 'fail_closed') throw new Error('complaints must fail closed');
const orders = interpretInsuranceAskQuery('disciplinary orders against an insurance agent in Illinois');
if (orders.query.mode !== 'fail_closed') throw new Error('IL orders must fail closed');
const best = interpretInsuranceAskQuery('best insurance company in Illinois');
if (best.query.mode !== 'fail_closed') throw new Error('ranking');
const chicago = interpretInsuranceAskQuery('safest insurance company in Chicago');
if (chicago.query.mode !== 'fail_closed') throw new Error('chicago ranking');
const naic = interpretInsuranceAskQuery('Find insurer NAIC code 10064');
if (naic.query.mode !== 'identifier') throw new Error('NAIC identifier path');
if (naic.query.identifier?.value !== '10064') throw new Error('NAIC value');

console.log('assert:il-ins-001 pass', snap.fingerprint.slice(0, 12));
