import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { interpretInsuranceAskQuery } from '../lib/insurance-ask/interpret';
import { STATE_RESEARCH } from '../lib/insurance-ask/recovery';
import { normalizedPublishedStatePath } from '../lib/seo/published-state-path';

const read = (p: string) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const snapshot = JSON.parse(read('lib/mississippi-intelligence/ms-ins-001.json'));
const page = read('app/mississippi/page.tsx');
const sitemap = read('app/sitemap.ts');
const companies = snapshot.licensedCompanies;
const entities = snapshot.producerEntities;
const ask = (q: string) => interpretInsuranceAskQuery(q);

assert.equal(companies.types.reduce((sum: number, row: { rows: number }) => sum + row.rows, 0), companies.rows);
assert.equal(companies.rows, 2129);
assert.equal(companies.uniqueLicenseNumbers, 2129);
assert.equal(companies.blankNaic + companies.nonemptyNaicRows, companies.rows);
assert.equal(companies.uniqueNonemptyNaic, 1521);
assert.notEqual(companies.uniqueNonemptyNaic, companies.rows);
assert.equal(companies.isRiskBearingInsurerCensus, false);
assert.equal(companies.typesPartitionTheList, true);
assert.equal(entities.rows, 10645);
assert.equal(entities.uniqueAgencyIds, 10645);
assert.equal(entities.mailMississippi, 1422);
assert.equal(entities.expirationOnOrAfterFileDate + entities.expirationBeforeFileDate, entities.rows);
assert.equal(entities.isIndividualProducer, false);
assert.equal(entities.isCompany, false);
assert.equal(entities.redownloaded, false);
assert.equal(entities.databaseReread, false);
assert.equal(entities.earlierExpirationIsInactiveCensus, false);
assert.equal(snapshot.notAcquired.individualProducers, 'NOT_ACQUIRED');
assert.equal(snapshot.notAcquired.adjusters, 'NOT_ACQUIRED');
assert.equal(snapshot.notAcquired.surplusLines, 'NOT_ACQUIRED');
assert.equal(snapshot.enforcement.orders, 'NOT_ACQUIRED');
assert.equal(snapshot.enforcement.nameOnlyAdverseJoins, 0);
assert.equal(snapshot.graphWrites, 0);
assert.equal(snapshot.newCanonicalOrganizations, 0);
assert.notEqual(companies.rows + entities.rows, companies.rows);
assert.equal(STATE_RESEARCH.MS, '/mississippi');
assert.equal(normalizedPublishedStatePath('/Mississippi'), '/mississippi');
assert.equal(normalizedPublishedStatePath('/mississippi'), null);
assert.equal(normalizedPublishedStatePath('/mississippi/jackson'), null);
assert.equal((sitemap.match(/'\/mississippi'/g) ?? []).length, 1);
assert.deepEqual(readdirSync(new URL('../app/mississippi', import.meta.url)), ['page.tsx']);
assert.match(page, /path: '\/mississippi'/);
assert.match(page, /2,129/);
assert.match(page, /10,645/);
assert.match(page, /NOT_ACQUIRED/);
assert.match(page, /does not publish one Mississippi insurance population/);
assert.doesNotMatch(page, /AggregateRating|ratingValue|Trust Score/);
assert.doesNotMatch(page, /12,774|12774/);
assert.doesNotMatch(page, /\/mississippi\/(?:jackson|gulfport|biloxi)/);

const companiesAsk = ask('how many insurance companies in Mississippi').query;
assert.equal(companiesAsk.mode, 'fail_closed');
assert.equal(companiesAsk.jurisdiction?.state, 'MS');
assert.match(companiesAsk.failReason ?? '', /2,129/);
assert.match(companiesAsk.failReason ?? '', /not a risk-bearing-insurer-only census/);
const agencies = ask('Mississippi insurance agencies').query;
assert.match(agencies.failReason ?? '', /10,645/);
assert.match(agencies.failReason ?? '', /not individual producers/);
assert.match(ask('Mississippi insurance producers').query.failReason ?? '', /NOT_ACQUIRED/);
assert.match(ask('Mississippi insurance adjusters').query.failReason ?? '', /NOT_ACQUIRED/);
assert.match(ask('Mississippi surplus lines').query.failReason ?? '', /NOT_ACQUIRED/);
assert.match(ask('best insurance company in Mississippi').query.failReason ?? '', /does not rank/);
assert.match(ask('insurance company Gulfport Mississippi').query.failReason ?? '', /geography only/);
assert.notEqual(ask('insurance company Jackson').query.jurisdiction?.state, 'MS');
assert.equal(ask('how many insurance companies in South Carolina').query.jurisdiction?.state, 'SC');
assert.notEqual(ask('insurance in missouri').query.jurisdiction?.state, 'MS');
assert.equal(ask('insurance in ms').query.jurisdiction?.state, 'MS');
console.log('MS-INS-001 PASS');
