export type GoldenClassification = 'PASS' | 'PARTIAL' | 'UNSUPPORTED_SAFE' | 'FAIL';
export type GoldenQuestion = { query: string; expected: GoldenClassification };

export const INSURANCE_SEARCH_GOLDEN_QUESTIONS: GoldenQuestion[] = [
  ['NPN 10391484','PASS'],['Find NPN 10391484','PASS'],['What is an NPN?','PASS'],['NAIC company code 12345','PASS'],['what is a legal insurer','PASS'],['agency vs insurer','PASS'],
  ['insurance agencies credentialed in Florida','PASS'],['insurance agencies credentialed in Texas','PASS'],['Florida agencies with Property and Casualty authority','PARTIAL'],['Texas agencies with Property authority','PASS'],['agencies with Life authority','PARTIAL'],['what is a line of authority','PASS'],['what is an insurance appointment','PASS'],['agencies appointed by State Farm','UNSUPPORTED_SAFE'],['agencies with appointments','UNSUPPORTED_SAFE'],
  ['licensed insurance companies in Florida','PARTIAL'],['licensed insurance companies in Texas','UNSUPPORTED_SAFE'],['how many insurance agencies are there','PASS'],['how many insurance producers are there','PASS'],['how many licensed insurance companies are there','PASS'],['how many Florida-credentialed agencies','PASS'],['how many Texas appointments','UNSUPPORTED_SAFE'],['how many Marketplace observations','PARTIAL'],['CMS Marketplace insurance evidence','PARTIAL'],['what does Marketplace registration evidence mean','PASS'],
  ['insurance agencies with complaints','PARTIAL'],['Texas insurance complaints','PARTIAL'],['insurance agencies with no complaints','UNSUPPORTED_SAFE'],['insurers with market conduct exams','PARTIAL'],['insurers with financial exams','PARTIAL'],['insurers with enforcement records','PARTIAL'],['insurers with rate filings','PARTIAL'],['compare Florida and Texas agency credentials','PASS'],['compare agencies and insurers','PARTIAL'],
  ['Florida homeowners insurance agencies','PARTIAL'],['auto insurance agencies in Florida','PARTIAL'],['life insurance agencies in Texas','PASS'],['health insurance agencies','PARTIAL'],['insurance agents near 33441','PASS'],['insurance agencies in ZIP 33441','PASS'],['homeowners insurance near me','PARTIAL'],['I need homeowners insurance in Boca Raton','PARTIAL'],
  ['I want to check the agency that quoted me','UNSUPPORTED_SAFE'],['Is this insurance agent licensed?','UNSUPPORTED_SAFE'],['Is this company an agency or an insurance company?','UNSUPPORTED_SAFE'],['Who actually underwrites my policy?','UNSUPPORTED_SAFE'],['Does this agency represent State Farm?','UNSUPPORTED_SAFE'],['Can this agency sell homeowners insurance?','UNSUPPORTED_SAFE'],['Is this insurer licensed in Florida?','UNSUPPORTED_SAFE'],['Does this agency serve Broward County?','UNSUPPORTED_SAFE'],['insurance companies serving my ZIP code','UNSUPPORTED_SAFE'],['insurers headquartered in Florida','UNSUPPORTED_SAFE'],['insurers domiciled in Florida','PARTIAL'],['insurer domicile meaning','PASS'],
  ['NFIP insurance agents','PARTIAL'],['NFIP certified agencies','UNSUPPORTED_SAFE'],['best insurance agency','UNSUPPORTED_SAFE'],['cheapest homeowners insurance','UNSUPPORTED_SAFE'],['safest insurer','UNSUPPORTED_SAFE'],['most trusted insurance agency','UNSUPPORTED_SAFE'],['best insurance company','UNSUPPORTED_SAFE'],['insurer with no complaints','UNSUPPORTED_SAFE'],['agency with a clean record','UNSUPPORTED_SAFE'],['insurance company with no enforcement','UNSUPPORTED_SAFE'],
  ['agent with NPN but no agency','UNSUPPORTED_SAFE'],['organization NPN','PARTIAL'],['producer NPN','PARTIAL'],['public producer profile','UNSUPPORTED_SAFE'],['find insurance producer NPN 10391484','PASS'],['insurance carrier appointment meaning','PASS'],
  ['NPN 12','UNSUPPORTED_SAFE'],['123456','UNSUPPORTED_SAFE'],['NAIC 10064','PASS'],['compare Florida and Massachusetts agency credentials','PASS'],['agencies credentialed in Vermont','PASS'],['agencies credentialed in Ohio','PASS'],['California admitted insurers','UNSUPPORTED_SAFE'],['New Jersey surplus lines insurers','UNSUPPORTED_SAFE'],['Washington authorized insurers','UNSUPPORTED_SAFE'],['licensed insurance agencies in Colorado','UNSUPPORTED_SAFE'],['Colorado insurance agents','UNSUPPORTED_SAFE'],['licensed insurance companies in Colorado','UNSUPPORTED_SAFE'],['county appointments in Florida','UNSUPPORTED_SAFE'],['property and casualty agencies in Massachusetts','PASS'],['Marketplace evidence for NPN 10391484 plan year 2026','PASS'],['<script>alert(1)</script>','UNSUPPORTED_SAFE'],["' OR 1=1 --",'UNSUPPORTED_SAFE'],['x'.repeat(500),'UNSUPPORTED_SAFE'],['','UNSUPPORTED_SAFE'],
].map(([query, expected]) => ({ query, expected })) as GoldenQuestion[];
